# Copyright (c) 2021-2024 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Slack PR Notification
on:
  # use pull_request_target to run on PRs from forks and have access to secrets
  pull_request_target:
    types: [labeled]

env:
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  channel: "onetbb"

permissions:
  pull-requests: read

jobs:
  rfc:
    name: RFC Notification
    runs-on: ubuntu-latest
    # Trigger when labeling a PR with "RFC"
    if: |
      github.event.action == 'labeled' &&
      contains(toJson(github.event.pull_request.labels.*.name), '"RFC"')
    steps: 
    - name: Notify Slack
      uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e # v1.26.0
      with:
        channel-id: ${{ env.channel }}
        slack-message: "${{ github.actor }} posted a RFC: ${{ github.event.pull_request.title }}. URL: ${{ github.event.pull_request.html_url }}"
